### ISSUE TITLE
HSE_VALUE should be defined through config.json or target.json config field

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-hal-st-stm32f401re#7]
Related https://github.com/ARMmbed/cmsis-core-stm32f401xe/issues/7

Right now the external oscillator frequency value is hardcoded withing the module.
In stm32f4xx_hal_conf.h
```C
#if !defined  (HSE_VALUE) 
  #define HSE_VALUE    ((uint32_t)8000000) /*!< Value of the External oscillator in Hz */
#endif /* HSE_VALUE */
```
In our case we use a 16Mhz one, so imho this parameter should be configurable without tinkering with the code.

@bcostm could you please have a look?

**Comment by bcostm** [comment]
Done
